on: push
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        shell: pwsh
        run: ./cli_windows.ps1
