on: push
jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --exclude SC2034,SC2086,SC2059,SC2046
      - name: Run tests
        run: |
          cd tests
          ./cli_unix.sh
  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tests
        run: |
          cd tests
          ./cli_unix.sh
        env:
          # Hardcode version to avoid GitHub API rate limit in MacStadium
          SECRETHUB_CLI_VERSION: 0.39.0
