on: push
jobs:
  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: --exclude SC2034,SC2086,SC2059,SC2046
      - name: Test
        run: |
          cd tests
          ./cli_unix.sh
